ci: update tests.yml

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -39,6 +39,24 @@ jobs:
       - name: Start Chrome Driver
         run: vendor/laravel/dusk/bin/chromedriver-linux &
 
+      - name: Install Hookdeck CLI
+        run: |
+          VERSION=0.10.1
+          FILE_NAME=hookdeck_${VERSION}_linux_amd64.tar.gz
+          URL=https://github.com/hookdeck/hookdeck-cli/releases/download/v${VERSION}/${FILE_NAME}
+          
+          curl -LO ${URL} || { echo "Failed to download ${FILE_NAME}"; exit 1; }
+          
+          tar -xvf ${FILE_NAME} || { echo "Failed to extract ${FILE_NAME}"; exit 1; }
+          
+          rm ${FILE_NAME}
+
+      - name: Configure Hookdeck Workspace
+        run: hookdeck ci --api-key ${{ secrets.HOOKDECK_API_KEY }}
+
+      - name: Listen to PayHere Webhook
+        run: hookdeck listen 8000 payhere &
+
       - name: Run Tests
         run: composer run test
         env:
